services:
  postgres-back-main:
    image: postgres:14-alpine
    container_name: postgres-back-main
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: main_db